AArch64: Allow implicit conversions between vectors
Allow implicit conversions between vectors with differing numbers of
elements and/or incompatible element types.

Otherwise build with GCC breaks on whatever vector uses:

error: cannot convert ‘uint16x4_t’ to ‘uint8x8_t’
error: cannot convert ‘uint16x8_t’ to ‘int16x8_t’
error: cannot convert ‘uint16x8_t’ to ‘uint8x16_t’
error: cannot convert ‘uint16x8_t’ to ‘__Uint8x16_t’
error: cannot convert ‘uint64x1_t’ to ‘uint16x4_t’