GCC requires arch extensions to be prefixed by '+' on AArch64
Clang does not have this requirement.

[  2%] Building CXX object src/system/CMakeFiles/system.dir/source/zip.cpp.o
/tmp/del/AltirraSDL/src/system/source/zip.cpp:602:73: error: arch extension ‘crc’ should be prefixed by ‘+’
  602 | uint32 VDCRC32Update_ARM64_CRC32(uint32 crc, const void *src, size_t len) {
      |                                                                         ^
/tmp/del/AltirraSDL/src/system/source/zip.cpp: In function ‘uint32 VDCRC32Update_ARM64_CRC32(uint32, const void*, size_t)’:
/tmp/del/AltirraSDL/src/system/source/zip.cpp:610:111: error: arch extension ‘crc’ should be prefixed by ‘+’
  610 |         const auto partialUpdate = [](uint32 crc, const void *src, size_t len) VD_CPU_TARGET_LAMBDA("crc") -> uint32 {
      |                                                                                                               ^~~~~~
gmake[2]: *** [src/system/CMakeFiles/system.dir/build.make:499: src/system/CMakeFiles/system.dir/source/zip.cpp.o] Błąd 1
gmake[1]: *** [CMakeFiles/Makefile2:460: src/system/CMakeFiles/system.dir/all] Błąd 2